//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace okboba.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("okboba.Resources.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生日.
        /// </summary>
        public static string Account_Birthdate {
            get {
                return ResourceManager.GetString("Account_Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电子邮件.
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忘记你的密码？.
        /// </summary>
        public static string Account_ForgotPassword {
            get {
                return ResourceManager.GetString("Account_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 城市.
        /// </summary>
        public static string Account_Location {
            get {
                return ResourceManager.GetString("Account_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绰号.
        /// </summary>
        public static string Account_Nickname {
            get {
                return ResourceManager.GetString("Account_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你的电子邮件.
        /// </summary>
        public static string Account_Placeholder_Email {
            get {
                return ResourceManager.GetString("Account_Placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你的密码.
        /// </summary>
        public static string Account_Placeholder_Password {
            get {
                return ResourceManager.GetString("Account_Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我是.
        /// </summary>
        public static string Account_Register_IAm {
            get {
                return ResourceManager.GetString("Account_Register_IAm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我找.
        /// </summary>
        public static string Account_Register_LookingFor {
            get {
                return ResourceManager.GetString("Account_Register_LookingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加照片.
        /// </summary>
        public static string Button_AddPhoto {
            get {
                return ResourceManager.GetString("Button_AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回答问题.
        /// </summary>
        public static string Button_AnswerQuestion {
            get {
                return ResourceManager.GetString("Button_AnswerQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑缩略图.
        /// </summary>
        public static string Button_EditThumbnail {
            get {
                return ResourceManager.GetString("Button_EditThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 喜爱用户.
        /// </summary>
        public static string Button_FavoriteUser {
            get {
                return ResourceManager.GetString("Button_FavoriteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加入！.
        /// </summary>
        public static string Button_Join {
            get {
                return ResourceManager.GetString("Button_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载以前的消息.
        /// </summary>
        public static string Button_LoadMessages {
            get {
                return ResourceManager.GetString("Button_LoadMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发信息.
        /// </summary>
        public static string Button_MessageUser {
            get {
                return ResourceManager.GetString("Button_MessageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一个.
        /// </summary>
        public static string Button_Next {
            get {
                return ResourceManager.GetString("Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新排列照片.
        /// </summary>
        public static string Button_RearrangePhotos {
            get {
                return ResourceManager.GetString("Button_RearrangePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳过问题.
        /// </summary>
        public static string Button_SkipQuestion {
            get {
                return ResourceManager.GetString("Button_SkipQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始交谈.
        /// </summary>
        public static string Button_StartConversation {
            get {
                return ResourceManager.GetString("Button_StartConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交.
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 变化回答.
        /// </summary>
        public static string Button_UpdateAnswer {
            get {
                return ResourceManager.GetString("Button_UpdateAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 体型.
        /// </summary>
        public static string Detail_Label_BodyType {
            get {
                return ResourceManager.GetString("Detail_Label_BodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事业与家庭.
        /// </summary>
        public static string Detail_Label_CareerAndFamily {
            get {
                return ResourceManager.GetString("Detail_Label_CareerAndFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购车情况.
        /// </summary>
        public static string Detail_Label_CarSituation {
            get {
                return ResourceManager.GetString("Detail_Label_CarSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色.
        /// </summary>
        public static string Detail_Label_Color {
            get {
                return ResourceManager.GetString("Detail_Label_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 穿着风格.
        /// </summary>
        public static string Detail_Label_DressStyle {
            get {
                return ResourceManager.GetString("Detail_Label_DressStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 饮酒.
        /// </summary>
        public static string Detail_Label_Drink {
            get {
                return ResourceManager.GetString("Detail_Label_Drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 饮食习惯.
        /// </summary>
        public static string Detail_Label_Eating {
            get {
                return ResourceManager.GetString("Detail_Label_Eating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 经济观念.
        /// </summary>
        public static string Detail_Label_EconomicConcept {
            get {
                return ResourceManager.GetString("Detail_Label_EconomicConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学历.
        /// </summary>
        public static string Detail_Label_Education {
            get {
                return ResourceManager.GetString("Detail_Label_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 锻炼习惯.
        /// </summary>
        public static string Detail_Label_Exercise {
            get {
                return ResourceManager.GetString("Detail_Label_Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 眼睛.
        /// </summary>
        public static string Detail_Label_Eye {
            get {
                return ResourceManager.GetString("Detail_Label_Eye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脸型.
        /// </summary>
        public static string Detail_Label_FaceType {
            get {
                return ResourceManager.GetString("Detail_Label_FaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对待感情.
        /// </summary>
        public static string Detail_Label_Feelings {
            get {
                return ResourceManager.GetString("Detail_Label_Feelings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 头发.
        /// </summary>
        public static string Detail_Label_Hair {
            get {
                return ResourceManager.GetString("Detail_Label_Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有无子女.
        /// </summary>
        public static string Detail_Label_HaveChildren {
            get {
                return ResourceManager.GetString("Detail_Label_HaveChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于宠物.
        /// </summary>
        public static string Detail_Label_HavePets {
            get {
                return ResourceManager.GetString("Detail_Label_HavePets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 健康情况.
        /// </summary>
        public static string Detail_Label_HealthCondition {
            get {
                return ResourceManager.GetString("Detail_Label_HealthCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身高.
        /// </summary>
        public static string Detail_Label_Height {
            get {
                return ResourceManager.GetString("Detail_Label_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 家务水平等级.
        /// </summary>
        public static string Detail_Label_Housework {
            get {
                return ResourceManager.GetString("Detail_Label_Housework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幽默感.
        /// </summary>
        public static string Detail_Label_Humour {
            get {
                return ResourceManager.GetString("Detail_Label_Humour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司行业.
        /// </summary>
        public static string Detail_Label_Industry {
            get {
                return ResourceManager.GetString("Detail_Label_Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 职业职位.
        /// </summary>
        public static string Detail_Label_Job {
            get {
                return ResourceManager.GetString("Detail_Label_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长度.
        /// </summary>
        public static string Detail_Label_Length {
            get {
                return ResourceManager.GetString("Detail_Label_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 居住情况.
        /// </summary>
        public static string Detail_Label_LivingSituation {
            get {
                return ResourceManager.GetString("Detail_Label_LivingSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 寻找.
        /// </summary>
        public static string Detail_Label_LookingFor {
            get {
                return ResourceManager.GetString("Detail_Label_LookingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宠物喜欢程度.
        /// </summary>
        public static string Detail_Label_LovePets {
            get {
                return ResourceManager.GetString("Detail_Label_LovePets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月薪.
        /// </summary>
        public static string Detail_Label_MonthlyIncome {
            get {
                return ResourceManager.GetString("Detail_Label_MonthlyIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大消费.
        /// </summary>
        public static string Detail_Label_MostMoney {
            get {
                return ResourceManager.GetString("Detail_Label_MostMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 肌肉.
        /// </summary>
        public static string Detail_Label_Muscle {
            get {
                return ResourceManager.GetString("Detail_Label_Muscle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 民族.
        /// </summary>
        public static string Detail_Label_Nationality {
            get {
                return ResourceManager.GetString("Detail_Label_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 婚姻状况.
        /// </summary>
        public static string Detail_Label_RelationshipStatus {
            get {
                return ResourceManager.GetString("Detail_Label_RelationshipStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宗教信仰.
        /// </summary>
        public static string Detail_Label_Religion {
            get {
                return ResourceManager.GetString("Detail_Label_Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 形状.
        /// </summary>
        public static string Detail_Label_Shape {
            get {
                return ResourceManager.GetString("Detail_Label_Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逛街购物.
        /// </summary>
        public static string Detail_Label_Shopping {
            get {
                return ResourceManager.GetString("Detail_Label_Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 皮肤.
        /// </summary>
        public static string Detail_Label_SkinType {
            get {
                return ResourceManager.GetString("Detail_Label_SkinType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作息时间.
        /// </summary>
        public static string Detail_Label_SleepSchedule {
            get {
                return ResourceManager.GetString("Detail_Label_SleepSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吸烟.
        /// </summary>
        public static string Detail_Label_Smoke {
            get {
                return ResourceManager.GetString("Detail_Label_Smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个性特征.
        /// </summary>
        public static string Detail_Label_Sociability {
            get {
                return ResourceManager.GetString("Detail_Label_Sociability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交际圈子.
        /// </summary>
        public static string Detail_Label_SocialCircle {
            get {
                return ResourceManager.GetString("Detail_Label_SocialCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发型.
        /// </summary>
        public static string Detail_Label_Style {
            get {
                return ResourceManager.GetString("Detail_Label_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脾气.
        /// </summary>
        public static string Detail_Label_Temper {
            get {
                return ResourceManager.GetString("Detail_Label_Temper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否要小孩.
        /// </summary>
        public static string Detail_Label_WantChildren {
            get {
                return ResourceManager.GetString("Detail_Label_WantChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作状态.
        /// </summary>
        public static string Detail_Label_WorkHours {
            get {
                return ResourceManager.GetString("Detail_Label_WorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外貌.
        /// </summary>
        public static string Detail_Section_Appearance {
            get {
                return ResourceManager.GetString("Detail_Section_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的信息.
        /// </summary>
        public static string Detail_Section_Basic {
            get {
                return ResourceManager.GetString("Detail_Section_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作.
        /// </summary>
        public static string Detail_Section_Job {
            get {
                return ResourceManager.GetString("Detail_Section_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生活方式.
        /// </summary>
        public static string Detail_Section_Lifestyle {
            get {
                return ResourceManager.GetString("Detail_Section_Lifestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个性.
        /// </summary>
        public static string Detail_Section_Personality {
            get {
                return ResourceManager.GetString("Detail_Section_Personality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电子邮件已经注册.
        /// </summary>
        public static string Error_EmailTaken {
            get {
                return ResourceManager.GetString("Error_EmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的电子邮件或密码.
        /// </summary>
        public static string Error_GenericLoginError {
            get {
                return ResourceManager.GetString("Error_GenericLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你没有照片, &lt;a href=&quot;{0}&quot;&gt;上载一长&lt;/a&gt;!.
        /// </summary>
        public static string Error_NoPhotos {
            get {
                return ResourceManager.GetString("Error_NoPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息你没有写你的信息，&lt;a href=&quot;{0}&quot;&gt;现在写&lt;/a&gt;！.
        /// </summary>
        public static string Error_NoProfileText {
            get {
                return ResourceManager.GetString("Error_NoProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你只回答了 {0} 个问题，&lt;a href=&quot;{1}&quot;&gt;回答多一点&lt;/a&gt;！.
        /// </summary>
        public static string Error_NoQuestionsAnswered {
            get {
                return ResourceManager.GetString("Error_NoQuestionsAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没什么可看这里.
        /// </summary>
        public static string Error_NothingHere {
            get {
                return ResourceManager.GetString("Error_NothingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎OK波霸！.
        /// </summary>
        public static string Error_Welcome {
            get {
                return ResourceManager.GetString("Error_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answered a question..
        /// </summary>
        public static string Feed_AnsweredQuestion {
            get {
                return ResourceManager.GetString("Feed_AnsweredQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edited their profile text..
        /// </summary>
        public static string Feed_EditedProfileText {
            get {
                return ResourceManager.GetString("Feed_EditedProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to joined! Send them a message!.
        /// </summary>
        public static string Feed_Joined {
            get {
                return ResourceManager.GetString("Feed_Joined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploaded a photo..
        /// </summary>
        public static string Feed_UploadedPhoto {
            get {
                return ResourceManager.GetString("Feed_UploadedPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敌对.
        /// </summary>
        public static string Match_Enemy {
            get {
                return ResourceManager.GetString("Match_Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 朋友.
        /// </summary>
        public static string Match_Friend {
            get {
                return ResourceManager.GetString("Match_Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匹配.
        /// </summary>
        public static string Match_Match {
            get {
                return ResourceManager.GetString("Match_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 把它们写一个可爱的消息.
        /// </summary>
        public static string Messaging_Compose_Placeholder {
            get {
                return ResourceManager.GetString("Messaging_Compose_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消息发送！.
        /// </summary>
        public static string Messaging_Sent_Confirmation {
            get {
                return ResourceManager.GetString("Messaging_Sent_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息主题.
        /// </summary>
        public static string Messaging_Subject_Placeholder {
            get {
                return ResourceManager.GetString("Messaging_Subject_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他.
        /// </summary>
        public static string Messaging_Them {
            get {
                return ResourceManager.GetString("Messaging_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你.
        /// </summary>
        public static string Messaging_You {
            get {
                return ResourceManager.GetString("Messaging_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览匹配.
        /// </summary>
        public static string Nav_BrowseMatches {
            get {
                return ResourceManager.GetString("Nav_BrowseMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提高比赛.
        /// </summary>
        public static string Nav_ImproveMatches {
            get {
                return ResourceManager.GetString("Nav_ImproveMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登出.
        /// </summary>
        public static string Nav_Logoff {
            get {
                return ResourceManager.GetString("Nav_Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接受.
        /// </summary>
        public static string Nav_Messages_Received {
            get {
                return ResourceManager.GetString("Nav_Messages_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回复.
        /// </summary>
        public static string Nav_Messages_Reply {
            get {
                return ResourceManager.GetString("Nav_Messages_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送.
        /// </summary>
        public static string Nav_Messages_Sent {
            get {
                return ResourceManager.GetString("Nav_Messages_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我保存的.
        /// </summary>
        public static string Nav_MyFavorites {
            get {
                return ResourceManager.GetString("Nav_MyFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的简历.
        /// </summary>
        public static string Nav_MyProfile {
            get {
                return ResourceManager.GetString("Nav_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 照片.
        /// </summary>
        public static string Nav_Photos {
            get {
                return ResourceManager.GetString("Nav_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人信息.
        /// </summary>
        public static string Nav_Profile {
            get {
                return ResourceManager.GetString("Nav_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 问题.
        /// </summary>
        public static string Nav_Questions {
            get {
                return ResourceManager.GetString("Nav_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择你的笑脸.
        /// </summary>
        public static string Photo_EditThumbnail_Title {
            get {
                return ResourceManager.GetString("Photo_EditThumbnail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新排列照片.
        /// </summary>
        public static string Photo_RearrangeModal_Title {
            get {
                return ResourceManager.GetString("Photo_RearrangeModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传您的照片.
        /// </summary>
        public static string Photo_UploadModal_Title {
            get {
                return ResourceManager.GetString("Photo_UploadModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 女.
        /// </summary>
        public static string Profile_Female {
            get {
                return ResourceManager.GetString("Profile_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 男.
        /// </summary>
        public static string Profile_Male {
            get {
                return ResourceManager.GetString("Profile_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有写.
        /// </summary>
        public static string Profile_Question_Empty {
            get {
                return ResourceManager.GetString("Profile_Question_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请写一些关于自己在这里.
        /// </summary>
        public static string Profile_Question_Placeholder {
            get {
                return ResourceManager.GetString("Profile_Question_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于你自己一点点.
        /// </summary>
        public static string Profile_Question1 {
            get {
                return ResourceManager.GetString("Profile_Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你做什么工作？上学？.
        /// </summary>
        public static string Profile_Question2 {
            get {
                return ResourceManager.GetString("Profile_Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你有什么爱好和兴趣？.
        /// </summary>
        public static string Profile_Question3 {
            get {
                return ResourceManager.GetString("Profile_Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你有什么想法？.
        /// </summary>
        public static string Profile_Question4 {
            get {
                return ResourceManager.GetString("Profile_Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的理想匹配.
        /// </summary>
        public static string Profile_Question5 {
            get {
                return ResourceManager.GetString("Profile_Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有点重要.
        /// </summary>
        public static string Question_ALittleImportant {
            get {
                return ResourceManager.GetString("Question_ALittleImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上述任何.
        /// </summary>
        public static string Question_AnyAbove {
            get {
                return ResourceManager.GetString("Question_AnyAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不重要.
        /// </summary>
        public static string Question_Irrelevant {
            get {
                return ResourceManager.GetString("Question_Irrelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like your match to answer?.
        /// </summary>
        public static string Question_Prompt_Acceptable {
            get {
                return ResourceManager.GetString("Question_Prompt_Acceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How important are your matches answers?.
        /// </summary>
        public static string Question_Prompt_Importance {
            get {
                return ResourceManager.GetString("Question_Prompt_Importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重要.
        /// </summary>
        public static string Question_SomewhatImportant {
            get {
                return ResourceManager.GetString("Question_SomewhatImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 很重要.
        /// </summary>
        public static string Question_VeryImportant {
            get {
                return ResourceManager.GetString("Question_VeryImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活跃用户.
        /// </summary>
        public static string Section_ActiveUsers {
            get {
                return ResourceManager.GetString("Section_ActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 近期活动.
        /// </summary>
        public static string Section_ActivityFeed {
            get {
                return ResourceManager.GetString("Section_ActivityFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存的用户.
        /// </summary>
        public static string Section_Favorites {
            get {
                return ResourceManager.GetString("Section_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匹配问题.
        /// </summary>
        public static string Section_MatchQuestions {
            get {
                return ResourceManager.GetString("Section_MatchQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息.
        /// </summary>
        public static string Section_Messages {
            get {
                return ResourceManager.GetString("Section_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推荐匹配.
        /// </summary>
        public static string Section_RecommendeMatches {
            get {
                return ResourceManager.GetString("Section_RecommendeMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天前.
        /// </summary>
        public static string Time_DaysAgo {
            get {
                return ResourceManager.GetString("Time_DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 现在.
        /// </summary>
        public static string Time_JustNow {
            get {
                return ResourceManager.GetString("Time_JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昨天.
        /// </summary>
        public static string Time_Yesterday {
            get {
                return ResourceManager.GetString("Time_Yesterday", resourceCulture);
            }
        }
    }
}
