//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace okboba.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("okboba.Resources.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电子邮件.
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绰号.
        /// </summary>
        public static string Account_Name {
            get {
                return ResourceManager.GetString("Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敌对.
        /// </summary>
        public static string Common_Enemy {
            get {
                return ResourceManager.GetString("Common_Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 朋友.
        /// </summary>
        public static string Common_Friend {
            get {
                return ResourceManager.GetString("Common_Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string Common_Login {
            get {
                return ResourceManager.GetString("Common_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匹配.
        /// </summary>
        public static string Common_Match {
            get {
                return ResourceManager.GetString("Common_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交.
        /// </summary>
        public static string Common_Submit {
            get {
                return ResourceManager.GetString("Common_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性格.
        /// </summary>
        public static string Nav_Personality {
            get {
                return ResourceManager.GetString("Nav_Personality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 照片.
        /// </summary>
        public static string Nav_Photos {
            get {
                return ResourceManager.GetString("Nav_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人信息.
        /// </summary>
        public static string Nav_Profile {
            get {
                return ResourceManager.GetString("Nav_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 问题.
        /// </summary>
        public static string Nav_Questions {
            get {
                return ResourceManager.GetString("Nav_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加照片.
        /// </summary>
        public static string Photo_AddPhoto {
            get {
                return ResourceManager.GetString("Photo_AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Photo_Delete {
            get {
                return ResourceManager.GetString("Photo_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Thumbnail.
        /// </summary>
        public static string Photo_EditThumbnail {
            get {
                return ResourceManager.GetString("Photo_EditThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your smiling face.
        /// </summary>
        public static string Photo_EditThumbnail_Caption {
            get {
                return ResourceManager.GetString("Photo_EditThumbnail_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rearrange Photos.
        /// </summary>
        public static string Photo_Rearrange {
            get {
                return ResourceManager.GetString("Photo_Rearrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Your Photo.
        /// </summary>
        public static string Photo_UploadYourPhoto {
            get {
                return ResourceManager.GetString("Photo_UploadYourPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于你自己一点点.
        /// </summary>
        public static string Profile_Question1 {
            get {
                return ResourceManager.GetString("Profile_Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你做什么工作？上学？.
        /// </summary>
        public static string Profile_Question2 {
            get {
                return ResourceManager.GetString("Profile_Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你有什么爱好和兴趣？.
        /// </summary>
        public static string Profile_Question3 {
            get {
                return ResourceManager.GetString("Profile_Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你有什么想法？.
        /// </summary>
        public static string Profile_Question4 {
            get {
                return ResourceManager.GetString("Profile_Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的理想匹配.
        /// </summary>
        public static string Profile_Question5 {
            get {
                return ResourceManager.GetString("Profile_Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有写.
        /// </summary>
        public static string Profile_Text_None {
            get {
                return ResourceManager.GetString("Profile_Text_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请写一些关于自己在这里.
        /// </summary>
        public static string Profile_Text_Prompt {
            get {
                return ResourceManager.GetString("Profile_Text_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 体型.
        /// </summary>
        public static string ProfileDetail_BodyType {
            get {
                return ResourceManager.GetString("ProfileDetail_BodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事业与家庭.
        /// </summary>
        public static string ProfileDetail_CareerAndFamily {
            get {
                return ResourceManager.GetString("ProfileDetail_CareerAndFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购车情况.
        /// </summary>
        public static string ProfileDetail_CarSituation {
            get {
                return ResourceManager.GetString("ProfileDetail_CarSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 穿着风格.
        /// </summary>
        public static string ProfileDetail_DressStyle {
            get {
                return ResourceManager.GetString("ProfileDetail_DressStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 饮酒.
        /// </summary>
        public static string ProfileDetail_Drink {
            get {
                return ResourceManager.GetString("ProfileDetail_Drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 饮食习惯.
        /// </summary>
        public static string ProfileDetail_Eating {
            get {
                return ResourceManager.GetString("ProfileDetail_Eating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 经济观念.
        /// </summary>
        public static string ProfileDetail_EconomicConcept {
            get {
                return ResourceManager.GetString("ProfileDetail_EconomicConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学历.
        /// </summary>
        public static string ProfileDetail_Education {
            get {
                return ResourceManager.GetString("ProfileDetail_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 锻炼习惯.
        /// </summary>
        public static string ProfileDetail_Exercise {
            get {
                return ResourceManager.GetString("ProfileDetail_Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 眼睛.
        /// </summary>
        public static string ProfileDetail_Eye {
            get {
                return ResourceManager.GetString("ProfileDetail_Eye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脸型.
        /// </summary>
        public static string ProfileDetail_FaceType {
            get {
                return ResourceManager.GetString("ProfileDetail_FaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对待感情.
        /// </summary>
        public static string ProfileDetail_Feelings {
            get {
                return ResourceManager.GetString("ProfileDetail_Feelings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 头发.
        /// </summary>
        public static string ProfileDetail_Hair {
            get {
                return ResourceManager.GetString("ProfileDetail_Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有无子女.
        /// </summary>
        public static string ProfileDetail_HaveChildren {
            get {
                return ResourceManager.GetString("ProfileDetail_HaveChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于宠物.
        /// </summary>
        public static string ProfileDetail_HavePets {
            get {
                return ResourceManager.GetString("ProfileDetail_HavePets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 健康情况.
        /// </summary>
        public static string ProfileDetail_HealthCondition {
            get {
                return ResourceManager.GetString("ProfileDetail_HealthCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身高.
        /// </summary>
        public static string ProfileDetail_Height {
            get {
                return ResourceManager.GetString("ProfileDetail_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 家务水平等级.
        /// </summary>
        public static string ProfileDetail_Housework {
            get {
                return ResourceManager.GetString("ProfileDetail_Housework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幽默感.
        /// </summary>
        public static string ProfileDetail_Humour {
            get {
                return ResourceManager.GetString("ProfileDetail_Humour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司行业.
        /// </summary>
        public static string ProfileDetail_Industry {
            get {
                return ResourceManager.GetString("ProfileDetail_Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 职业职位.
        /// </summary>
        public static string ProfileDetail_Job {
            get {
                return ResourceManager.GetString("ProfileDetail_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 居住情况.
        /// </summary>
        public static string ProfileDetail_LivingSituation {
            get {
                return ResourceManager.GetString("ProfileDetail_LivingSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 寻找.
        /// </summary>
        public static string ProfileDetail_LookingFor {
            get {
                return ResourceManager.GetString("ProfileDetail_LookingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宠物喜欢程度.
        /// </summary>
        public static string ProfileDetail_LovePets {
            get {
                return ResourceManager.GetString("ProfileDetail_LovePets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月薪.
        /// </summary>
        public static string ProfileDetail_MonthlyIncome {
            get {
                return ResourceManager.GetString("ProfileDetail_MonthlyIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大消费.
        /// </summary>
        public static string ProfileDetail_MostMoney {
            get {
                return ResourceManager.GetString("ProfileDetail_MostMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 肌肉.
        /// </summary>
        public static string ProfileDetail_Muscle {
            get {
                return ResourceManager.GetString("ProfileDetail_Muscle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 民族.
        /// </summary>
        public static string ProfileDetail_Nationality {
            get {
                return ResourceManager.GetString("ProfileDetail_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 婚姻状况.
        /// </summary>
        public static string ProfileDetail_RelationshipStatus {
            get {
                return ResourceManager.GetString("ProfileDetail_RelationshipStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宗教信仰.
        /// </summary>
        public static string ProfileDetail_Religion {
            get {
                return ResourceManager.GetString("ProfileDetail_Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逛街购物.
        /// </summary>
        public static string ProfileDetail_Shopping {
            get {
                return ResourceManager.GetString("ProfileDetail_Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 皮肤.
        /// </summary>
        public static string ProfileDetail_SkinType {
            get {
                return ResourceManager.GetString("ProfileDetail_SkinType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作息时间.
        /// </summary>
        public static string ProfileDetail_SleepSchedule {
            get {
                return ResourceManager.GetString("ProfileDetail_SleepSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吸烟.
        /// </summary>
        public static string ProfileDetail_Smoke {
            get {
                return ResourceManager.GetString("ProfileDetail_Smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个性特征.
        /// </summary>
        public static string ProfileDetail_Sociability {
            get {
                return ResourceManager.GetString("ProfileDetail_Sociability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交际圈子.
        /// </summary>
        public static string ProfileDetail_SocialCircle {
            get {
                return ResourceManager.GetString("ProfileDetail_SocialCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脾气.
        /// </summary>
        public static string ProfileDetail_Temper {
            get {
                return ResourceManager.GetString("ProfileDetail_Temper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否要小孩.
        /// </summary>
        public static string ProfileDetail_WantChildren {
            get {
                return ResourceManager.GetString("ProfileDetail_WantChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作状态.
        /// </summary>
        public static string ProfileDetail_WorkHours {
            get {
                return ResourceManager.GetString("ProfileDetail_WorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有点重要.
        /// </summary>
        public static string Question_ALittleImportant {
            get {
                return ResourceManager.GetString("Question_ALittleImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上述任何.
        /// </summary>
        public static string Question_Any {
            get {
                return ResourceManager.GetString("Question_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不重要.
        /// </summary>
        public static string Question_Irrelevant {
            get {
                return ResourceManager.GetString("Question_Irrelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like your match to answer?.
        /// </summary>
        public static string Question_Prompt_Acceptable {
            get {
                return ResourceManager.GetString("Question_Prompt_Acceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How important are your matches answers?.
        /// </summary>
        public static string Question_Prompt_Importance {
            get {
                return ResourceManager.GetString("Question_Prompt_Importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重要.
        /// </summary>
        public static string Question_SomewhatImportant {
            get {
                return ResourceManager.GetString("Question_SomewhatImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 很重要.
        /// </summary>
        public static string Question_VeryImportant {
            get {
                return ResourceManager.GetString("Question_VeryImportant", resourceCulture);
            }
        }
    }
}
