//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace okboba.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("okboba.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电子邮件.
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绰号.
        /// </summary>
        public static string Account_Name {
            get {
                return ResourceManager.GetString("Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string Common_Login {
            get {
                return ResourceManager.GetString("Common_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交.
        /// </summary>
        public static string Common_Submit {
            get {
                return ResourceManager.GetString("Common_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于你自己一点点.
        /// </summary>
        public static string Profile_Question1 {
            get {
                return ResourceManager.GetString("Profile_Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你做什么工作？上学？.
        /// </summary>
        public static string Profile_Question2 {
            get {
                return ResourceManager.GetString("Profile_Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你有什么爱好和兴趣？.
        /// </summary>
        public static string Profile_Question3 {
            get {
                return ResourceManager.GetString("Profile_Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你有什么想法？.
        /// </summary>
        public static string Profile_Question4 {
            get {
                return ResourceManager.GetString("Profile_Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的理想匹配.
        /// </summary>
        public static string Profile_Question5 {
            get {
                return ResourceManager.GetString("Profile_Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有点重要.
        /// </summary>
        public static string Question_ALittleImportant {
            get {
                return ResourceManager.GetString("Question_ALittleImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上述任何.
        /// </summary>
        public static string Question_Any {
            get {
                return ResourceManager.GetString("Question_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不重要.
        /// </summary>
        public static string Question_Irrelevant {
            get {
                return ResourceManager.GetString("Question_Irrelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重要.
        /// </summary>
        public static string Question_SomewhatImportant {
            get {
                return ResourceManager.GetString("Question_SomewhatImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 很重要.
        /// </summary>
        public static string Question_VeryImportant {
            get {
                return ResourceManager.GetString("Question_VeryImportant", resourceCulture);
            }
        }
    }
}
